apiVersion: v1
kind: ConfigMap
metadata:
  name: cwagent-config
  namespace: default
data:
  cwagentconfig.json: |
    {
      "logs": {
        "metrics_collected": {
          "cpu": {
            "measurement": [
              "cpu_usage_idle",
              "cpu_usage_iowait",
              "cpu_usage_user",
              "cpu_usage_system"
            ],
            "metrics_collection_interval": 60
          },
          "mem": {
            "measurement": [
              "mem_used_percent"
            ],
            "metrics_collection_interval": 60
          }
        },
        "force_flush_interval": 5
      }
    }