apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-app.fullname" . | default "hello-app" }}
  labels:
    app.kubernetes.io/name: {{ include "hello-app.name" . | default "hello-app" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hello-app.name" . | default "hello-app" }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hello-app.name" . | default "hello-app" }}
    spec:
      containers:
        - name: {{ include "hello-app.name" . | default "hello-app" }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
