apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  labels:
    app.kubernetes.io/name: hello-app
spec:
  replicas: { .Values.replicaCount }
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-app
    spec:
      containers:
        - name: hello-app
          image: "{ .Values.image.repository }:{ .Values.image.tag }"
          imagePullPolicy: { .Values.image.pullPolicy }
          ports:
            - containerPort: 8080
          livenessProbe:
            {- toYaml .Values.livenessProbe | nindent 12 }
          readinessProbe:
            {- toYaml .Values.readinessProbe | nindent 12 }
          resources:
            {- toYaml .Values.resources | nindent 12 }
