replicaCount: 2

image:
  repository: 740092415723.dkr.ecr.eu-west-1.amazonaws.com/app
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

livenessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

irsaRoleArn: "arn:aws:iam::740092415723:role/eks-cloudwatch-reader"  # Fill this with the output from Terraform

awsRegion: "eu-west-1"

clusterName: "eks-dev"
